# -*- coding: utf-8 -*-
"""Tipe Data Casting (31 maret).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14ace2-vBPQ9gPIfAIsePAOKnEthQxXsa

**CASTING**
"""

nama = 'Lendis Fabri'

"""**Memeriksa Tipe Data**"""

nama = 'Budi'
usia = '20'
lajang = 'True'

print(type(nama))
print(type(usia))
print(type(lajang))

"""**Konversi Tipe Data**"""

usia = input('Masukkan usia anda:')

print(type(usia))

panjang = input('Masukkan panjang:')
lebar = input('Masukkan lebar:')

luas = int(panjang) * int(lebar)

print('luas =',luas)

"""**Konversi Tipe Data Secara Eksplisit**

untuk tipe data primitif, kita bisa memanggil fungsi berikut:
- int() = untuk konversi data ke integer
- float() = untuk konversi data ke float
- bool() = untuk konversi data ke bool
- str() = untuk konversi data string

Untuk tipe data lain, kita bisa memakai fungsi berikut
- list() = untuk list
- set() = untuk set
- tuple() = untuk tuple

**Konversi tipe data implisit**
"""

a = 10 / 2
print(type(a))

b = 1 /2
print(type(b))

kata = 'jeruk' * 5
print(kata)

"""**Konversi String Ke Numerik**"""

panjang = int(input('masukkan panjang: '))
lebar = float(input('masukkan lebar: '))

print('luas =', panjang * lebar)

"""**Konversi numerik ke string**"""

nama = 'gita'
tahun_lahir = 2006

print(nama + ' lahir di tahun ' + str(tahun_lahir))